name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - '*.md'

jobs:
    lint:
        name: Format Checks
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
                  cache-dependency-path: package.json
            - name: Install
              run: |
                  npm install --ignore-scripts

            - name: Lint
              run: |
                  npm run test:lint

            - name: Format
              run: |
                  npm run test:format

    test:
        name: Testing
        needs: lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
                  cache-dependency-path: package.json
            - name: Install
              run: |
                  npm install --ignore-scripts

            - name: Testing
              run: |
                  npm test
